name: sentry_demo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sentry_flutter: ^6.9.1
  cupertino_icons: ^1.0.2
  firebase_crashlytics: ^2.8.10
  firebase_core: ^1.22.0
  faker: ^2.0.0
  modal_bottom_sheet: ^2.1.2
  flutter_speed_dial: ^6.0.0
  keyboard_dismisser: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true